title: Hosea's IT Lab Journey
description: IT Support to Cybersecurity Portfolio
baseurl: ""
url: "https://yourusername.github.io"
theme: portfolyou
author:
  name: Hosea
  email: your.email@example.com
  github: yourusername
  linkedin: yourlinkedin
